dataset: 
  training: training.tfrecord
  validation: validation.tfrecord
  test: test.tfrecord

geometry: 
  intersections: 4
  max_distance: 15
  radius: 0.075
  shape: SPHERE

network: 
  activation: selu
  structure: 
    - [4]
    - [4]
    - [4]
    - [4]
    - [4]
    - [4]
    - [4]
    - [4]
    - [4]
    - [4]
    - [] # Convolution only as the number of classes is automatically added as the final layer of the network
  classes: 
    - [ball, [255, 255, 255]]
    - [environment, [0, 0, 0]]

training:
  epochs: 5
  batch_size: 5
  learning_rate: 0.001
  shuffle_size: 10
  save_frequency: 250
  adversary:
    learning_rate: 0.1
    structure_multiplier: 2
  validation:
    batch_size: 200
    progress_images: 10
    frequency: 50
    image_frequency: 250
  variants: {}
  #   image: 
  #     brightness: { 'mean': 0, 'stddev': 0.0 }
  #     contrast: { 'mean': 0, 'stddev': 0.0 }
  #     saturation: { 'mean': 0, 'stddev': 0.0 }
  #     gamma: { 'mean': 1, 'stddev': 0.0 }
  #     hue: { 'mean': 0, 'stddev': 0.0 }
  #   mesh: 
  #     height: { 'mean': 0, 'stddev': 0.0 }
  #     rotation: { 'mean': 0, 'stddev': 0.0 }
